# Generated by Django 5.1.5 on 2025-06-17 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutus", "0002_alter_aboutuspage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="aboutuspage",
            name="headline_first",
        ),
        migrations.RemoveField(
            model_name="aboutuspage",
            name="headline_second",
        ),
    ]
