# Generated by Django 5.1.5 on 2025-06-17 09:28

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aboutus", "0003_remove_aboutuspage_headline_first_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutuspage",
            name="page_buttons",
            field=wagtail.fields.StreamField(
                [("page", 0)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {
                            "page_type": [
                                "achievements.AchievementArchivePage",
                                "mediapublications.MediaPublicationsPage",
                            ]
                        },
                    )
                },
                null=True,
                verbose_name="Gumbi s povezavami do strani",
            ),
        ),
    ]
