apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-www
spec:
  redirectRegex:
    regex: ^https?://www.pravna-mreza.si/(.*)
    replacement: https://pravna-mreza.si/${1}
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: enable-cors
spec:
  headers:
    accessControlAllowOriginList:
      - "https://pravna-mreza.si"
    accessControlAllowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    accessControlAllowHeaders:
      - "*"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pravnamreza
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    traefik.ingress.kubernetes.io/router.middlewares: |
      traefik-redirect-to-https@kubernetescrd,
      pravnamreza-redirect-www@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - pravna-mreza.si
        - www.pravna-mreza.si
      secretName: pravnamreza-tls
  rules:
    - host: pravna-mreza.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pravnamreza
                port:
                  number: 8000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pravnamreza-nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    traefik.ingress.kubernetes.io/router.middlewares: |
      pravnamreza-enable-cors@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - files.pravna-mreza.si
      secretName: pravnamreza-nginx-tls
  rules:
    - host: files.pravna-mreza.si
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pravnamreza-nginx
                port:
                  number: 80
