apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pravnamreza
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: pravnamreza
    newName: rg.fr-par.scw.cloud/djnd/pravna-mreza.si
    newTag: '9da727e24542877ab7a193386e340307bce5351a'
