apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pravnamreza
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: pravnamreza
    newName: rg.fr-par.scw.cloud/djnd/pravna-mreza.si
    newTag: 'dd0f9b851aef9768e8043783b7a7598f2e5adbfa'
