apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pravnamreza
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: pravnamreza
    newName: rg.fr-par.scw.cloud/djnd/pravna-mreza.si
    newTag: 'a2f2d6990ac0d1ea0e5b8a7c91fc606e791e3f79'
