# Generated by Django 5.1.5 on 2025-06-17 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0005_auto_20240806_0948"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monitoringarchivepage",
            name="headline_first",
        ),
        migrations.RemoveField(
            model_name="monitoringarchivepage",
            name="headline_second",
        ),
    ]
