# Generated by Django 5.1.5 on 2025-06-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitoring", "0006_remove_monitoringarchivepage_headline_first_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="monitoringpage",
            name="old_migrated_page_path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
