# Generated by Django 5.1.5 on 2025-06-05 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0047_auto_20240806_0948"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="infopush",
            options={"verbose_name": "Infopush", "verbose_name_plural": "Infopushi"},
        ),
        migrations.AlterModelOptions(
            name="objava",
            options={
                "verbose_name": "Medijsko pojavljanje",
                "verbose_name_plural": "Medijska pojavljanja",
            },
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="intro_image",
        ),
        migrations.RemoveField(
            model_name="infopush",
            name="page_text",
        ),
        migrations.AddField(
            model_name="infopush",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Slika (neobvezno)",
            ),
        ),
        migrations.AlterField(
            model_name="infopush",
            name="title",
            field=models.TextField(default="(empty)", verbose_name="Naslov"),
            preserve_default=False,
        ),
    ]
