# Generated by Django 5.1.5 on 2025-06-05 08:55

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0048_alter_infopush_options_alter_objava_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="intro_boxes",
            field=wagtail.fields.StreamField(
                [("box", 2)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.images.blocks.ImageChooserBlock",
                        (),
                        {"label": "Slika"},
                    ),
                    1: ("wagtail.blocks.CharBlock", (), {"label": "Besedilo"}),
                    2: (
                        "wagtail.blocks.StructBlock",
                        [[("image", 0), ("text", 1)]],
                        {"label": "Kvadratek"},
                    ),
                },
                null=True,
                verbose_name="Uvodni kvadratki",
            ),
        ),
        migrations.AlterField(
            model_name="homepage",
            name="intro_text",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Uvodno besedilo"
            ),
        ),
    ]
