# Generated by Django 5.1.5 on 2025-06-06 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0049_homepage_intro_boxes_alter_homepage_intro_text"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Objava",
            new_name="Publication",
        ),
    ]
