# Generated by Django 5.1.5 on 2025-06-15 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0050_rename_objava_publication"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MaintenancePage",
        ),
    ]
