# Generated by Django 5.1.5 on 2025-06-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0051_delete_maintenancepage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homepage",
            name="news_section_archive_link",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="news_section_archive_link_title",
        ),
        migrations.RemoveField(
            model_name="homepage",
            name="news_section_title",
        ),
        migrations.AddField(
            model_name="newsletter",
            name="newsletter_email_label",
            field=models.TextField(blank=True, verbose_name="Email naslov oznaka"),
        ),
    ]
