# Generated by Django 5.1.5 on 2025-06-16 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0052_remove_homepage_news_section_archive_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="footersettings",
            name="facebook_link",
        ),
        migrations.RemoveField(
            model_name="footersettings",
            name="footer_text",
        ),
        migrations.RemoveField(
            model_name="footersettings",
            name="instagram_link",
        ),
        migrations.RemoveField(
            model_name="footersettings",
            name="twitter_link",
        ),
    ]
