# Generated by Django 5.1.5 on 2025-06-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0053_remove_footersettings_facebook_link_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="newsletterpage",
            name="headline_first",
        ),
        migrations.RemoveField(
            model_name="newsletterpage",
            name="headline_second",
        ),
    ]
