# Generated by Django 5.1.5 on 2025-06-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0054_remove_newsletterpage_headline_first_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NewsletterPage",
        ),
    ]
