# Generated by Django 5.1.5 on 2025-06-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0055_delete_newsletterpage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="genericpage",
            name="headline_first",
        ),
        migrations.RemoveField(
            model_name="genericpage",
            name="headline_second",
        ),
    ]
