# Generated by Django 5.1.5 on 2025-06-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0010_alter_achievement_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievementarchivepage",
            name="headline_first",
        ),
        migrations.RemoveField(
            model_name="achievementarchivepage",
            name="headline_second",
        ),
    ]
