# Generated by Django 5.1.5 on 2025-06-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_auto_20240806_0948"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projectsarchivepage",
            name="headline_first",
        ),
        migrations.RemoveField(
            model_name="projectsarchivepage",
            name="headline_second",
        ),
    ]
