# Generated by Django 5.1.5 on 2025-06-16 18:33

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_remove_projectsarchivepage_headline_first_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectsarchivepage",
            name="archived_projects",
            field=wagtail.fields.StreamField(
                [("project", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["projects.ProjectPage"]},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("project", 0)]], {}),
                },
                null=True,
                verbose_name="Arhivirani projekti",
            ),
        ),
        migrations.AddField(
            model_name="projectsarchivepage",
            name="archived_projects_title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Naslov arhiviranih projektov",
            ),
        ),
        migrations.AddField(
            model_name="projectsarchivepage",
            name="projects_title",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Naslov aktualnih projektov",
            ),
        ),
        migrations.AlterField(
            model_name="projectsarchivepage",
            name="projects",
            field=wagtail.fields.StreamField(
                [("project", 1)],
                blank=True,
                block_lookup={
                    0: (
                        "wagtail.blocks.PageChooserBlock",
                        (),
                        {"page_type": ["projects.ProjectPage"]},
                    ),
                    1: ("wagtail.blocks.StructBlock", [[("project", 0)]], {}),
                },
                null=True,
                verbose_name="Aktualni projekti",
            ),
        ),
    ]
