# Generated by Django 5.1.5 on 2025-06-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("novice", "0010_alter_novicapage_body"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="novicaarchivepage",
            name="headline_first",
        ),
        migrations.RemoveField(
            model_name="novicaarchivepage",
            name="headline_second",
        ),
    ]
