# Generated by Django 5.1.5 on 2025-06-17 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mediapublications", "0002_auto_20211226_2136"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediapublicationspage",
            name="headline_first",
        ),
        migrations.RemoveField(
            model_name="mediapublicationspage",
            name="headline_second",
        ),
    ]
