# Generated by Django 5.1.5 on 2025-06-06 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_auto_20240806_0948"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Author",
            new_name="BlogAuthor",
        ),
    ]
