# Generated by Django 5.1.5 on 2025-06-06 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_rename_author_blogauthor"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(verbose_name="Ime")),
            ],
            options={
                "verbose_name": "Oznaka",
                "verbose_name_plural": "Oznake",
            },
        ),
        migrations.AlterModelOptions(
            name="blogarchivepage",
            options={
                "verbose_name": "Seznam objav",
                "verbose_name_plural": "Seznami objav",
            },
        ),
        migrations.AlterModelOptions(
            name="blogauthor",
            options={"verbose_name": "Avtor", "verbose_name_plural": "Avtorji"},
        ),
        migrations.AlterModelOptions(
            name="blogpage",
            options={"verbose_name": "Objava", "verbose_name_plural": "Objave"},
        ),
        migrations.AlterField(
            model_name="blogauthor",
            name="name",
            field=models.TextField(verbose_name="Ime"),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="tag",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="blog.blogtag",
                verbose_name="Oznaka",
            ),
        ),
    ]
