# Generated by Django 5.1.5 on 2025-06-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0019_blogtag_alter_blogarchivepage_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="old_migrated_page_path",
            field=models.TextField(blank=True, null=True),
        ),
    ]
