# Generated by Django 5.1.5 on 2025-06-16 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0020_blogpage_old_migrated_page_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blogarchivepage",
            name="headline_first",
        ),
        migrations.RemoveField(
            model_name="blogarchivepage",
            name="headline_second",
        ),
    ]
