# Generated by Django 5.1.5 on 2025-06-19 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0021_remove_blogarchivepage_headline_first_and_more"),
        ("wagtailcore", "0094_alter_page_locale"),
        ("wagtailimages", "0027_image_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsletterArchivePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "headline_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="wagtailimages.image",
                        verbose_name="Slika na naslovnici",
                    ),
                ),
            ],
            options={
                "verbose_name": "Seznam novičnikov",
                "verbose_name_plural": "Seznami novičnikov",
            },
            bases=("wagtailcore.page",),
        ),
    ]
